parameters:
#    ll_barter.example.class: LL\BarterBundle\Example

services:
#    ll_barter.example:
#        class: %ll_barter.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
